/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapi5SitemapPlugin from "strapi-5-sitemap-plugin/strapi-admin";
import strapiImportExport from "strapi-import-export/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor: ckeditor,
    "users-permissions": usersPermissions,
    "strapi-5-sitemap-plugin": strapi5SitemapPlugin,
    "strapi-import-export": strapiImportExport,
  },
});
